### ISSUE TITLE
Question about capital cost recovery methods

### ISSUE THREAD

**Issue by jdebacker** [TaxFoundation/capital-cost-recovery#4]
Two of the capital-cost-recovery methods described in `README.md` are not totally clear to me and I am not familiar enough with methods across the OECD to infer what is correct:

1. "SL2 - Straight-Line Method with Changing Rates": Does this represent rates that are known to change ahead of time (e.g., a firm makes an investment knowing they can recover 20% of the cost for the first two years and then 10% of the cost after that time (until the item is full depreciated)) or does this method reflect ex-post rate changes (e.g., a firm made and investment in year t under tax law that allowed one to depreciate the asset under a SL method at 20% per year, but a law change at t+k only allows SL at 10% per year (and investments already in place were not grandfathered)?
2. "InitialDB - Declining-Balance Method with an Initial Allowance": Is this method the same as DB with bonus depreciation?

If I've missed a document that outlines the equations underlying these methods, please point me towards that.  I can see equations in the R code, but wanted to understand them conceptually rather than work backwards from the source code.

Thanks!

**Comment by elkeasen** [comment]
To answer your questions:
1. Your first explanation for "SL2 - Straight-Line Method with Changing Rates" is correct--it's a known change ahead of time. For example, under current law a country may allow its businesses to depreciate buildings at 20% in the first year and then at 10% in the following eight years (straight-line method).
2. "InitialDB - Declining-Balance Method with an Initial Allowance" means that the declining-balance method is applied, but there is higher depreciation rate in the first year. E.g., Canada currently allows buildings to be written off at 12% in the first year, and then at 4% thereafter (using the declining-balance method).

**Comment by jdebacker** [comment]
Excellent - thanks @elkeasen!
